

import pygame
pygame.init()
pygame.font.init()

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
BLUE = (0, 255, 0)
GREEN = (0, 0, 255)

FPS = 240

MAT_WIDTH, MAT_HEIGHT = 300, 350
WIN_WIDTH, WIN_HEIGHT = 600, 700
MAT_ROWS = MAT_COLS = 50
TOOLBAR_HEIGHT = MAT_HEIGHT - MAT_WIDTH
MAT_PIXEL_SIZE = MAT_WIDTH // MAT_COLS
MAT = None

KERNEL_SIZE = 7
KERNEL_WIDTH = 200
KERNEL_PAD = 50
KERNEL_PIXEL_SIZE = KERNEL_WIDTH // KERNEL_SIZE
KERNEL_START_X, KERNEL_START_Y = 350, 50
KERNEL = None


OUTPUT_SIZE = MAT_ROWS - (KERNEL_SIZE - 1)
OUTPUT_WIDTH = 275
OUTPUT_PIXEL_SIZE = OUTPUT_WIDTH // OUTPUT_SIZE
OUTPUT_START_X, OUTPUT_START_Y = 162, 400
OUTPUT = None

BG_COLOR = WHITE

DRAW_GRID_LINES = True

def get_font(size):
    return pygame.font.SysFont("comicsans", size)
